# Generated by Django 4.1.2 on 2022-11-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, choices=[('Terror', 'Terror'), ('Suspense', 'Suspense'), ('Ação', 'Ação'), ('Desenho animado', 'Desenho animado')], max_length=100, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiacao', models.CharField(blank=True, choices=[('AFI Awards', 'AFI Awards'), ('Oscar', 'Oscar'), ('PGA', 'PGA'), ('BAFTA', 'BAFTA')], max_length=100, verbose_name='Premiações')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
