# Generated by Django 4.1.2 on 2022-11-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_genero_premio_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.genero'),
        ),
    ]
