# Generated by Django 4.1.2 on 2022-11-22 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_filme_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='premio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.premio'),
        ),
    ]
