# Generated by Django 4.1.2 on 2022-11-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_filme_premio'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentario',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.genero'),
        ),
        migrations.AddField(
            model_name='documentario',
            name='premio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.premio'),
        ),
        migrations.AddField(
            model_name='serie',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.genero'),
        ),
        migrations.AddField(
            model_name='serie',
            name='premio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.premio'),
        ),
    ]
