# Generated by Django 4.1.2 on 2022-11-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_rename_atores_diretor_alter_diretor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='episodios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Episódios'),
        ),
        migrations.AddField(
            model_name='serie',
            name='temporada',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temporadas'),
        ),
    ]
