# Generated by Django 4.1.2 on 2022-11-29 20:11

import aplic.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0012_alter_filme_imagem_alter_genero_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=aplic.models.get_file_path, variations={'thumb': {'crop': True, 'height': 620, 'width': 620}}, verbose_name='Imagem'),
        ),
    ]
